# Patch ExternalSecrets to use dev environment secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-db
spec:
  data:
    - secretKey: dbpassword
      remoteRef:
        key: stack-ai/dev/aurora
        property: password
    - secretKey: jwtsecret
      remoteRef:
        key: stack-ai/dev/supabase
        property: jwt-secret
    - secretKey: anonkey
      remoteRef:
        key: stack-ai/dev/supabase
        property: anon-key
    - secretKey: servicerolekey
      remoteRef:
        key: stack-ai/dev/supabase
        property: service-role-key
    - secretKey: dashboardusername
      remoteRef:
        key: stack-ai/dev/supabase
        property: dashboard-username
    - secretKey: dashboardpassword
      remoteRef:
        key: stack-ai/dev/supabase
        property: dashboard-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-smtp
spec:
  data:
    - secretKey: smtp-host
      remoteRef:
        key: stack-ai/dev/smtp
        property: host
    - secretKey: smtp-port
      remoteRef:
        key: stack-ai/dev/smtp
        property: port
    - secretKey: smtp-user
      remoteRef:
        key: stack-ai/dev/smtp
        property: user
    - secretKey: smtp-pass
      remoteRef:
        key: stack-ai/dev/smtp
        property: password
    - secretKey: smtp-sender
      remoteRef:
        key: stack-ai/dev/smtp
        property: sender
